### ISSUE TITLE
Query editor behaves strangely in Safari

### ISSUE THREAD

**Issue by zwass** [kolide/fleet#1324]
Strange rendering while typing

![editor](https://cloud.githubusercontent.com/assets/575602/23440660/2d5785b0-fdd2-11e6-8fa8-f76d24d4c3e9.gif)
![editor2](https://cloud.githubusercontent.com/assets/575602/23441210/d1ad5254-fdd5-11e6-928a-ede501511b65.gif)

**Comment by mwild1** [comment]
For the record I'm seeing similar issues on Firefox 64, Ubuntu.

**Comment by mwild1** [comment]
Further research:

It looks like the issue is https://github.com/ajaxorg/ace/issues/460 - in summary, that Ace only supports monospaced fonts.

I see the current CSS rule is for `'Source Code Pro', monospace`. It looks like Source Code Pro is monospace, and Firefox claims to be using it for that element - so it should work. But if I change the rule to just `monospace` it loads 'Deja Vu Sans Mono' instead and suddenly the glitches are fixed.

**Comment by mwild1** [comment]
I've tried to prepare various fixes based on the insightful discussion over at another project that experiences this issue: https://github.com/contao/core/issues/7103

However so far I haven't been able to make it work, except for this patch:

```
diff --git a/frontend/components/KolideAce/theme.css b/frontend/components/KolideAce/theme.css
index 3a21e048..b3bb3099 100644
--- a/frontend/components/KolideAce/theme.css
+++ b/frontend/components/KolideAce/theme.css
@@ -1,5 +1,4 @@
 .ace_editor.ace-kolide {
-  font-family: 'SourceCodePro', monospace;
   font-size: 14px;
   background-color: #fcfcff;
   color: #66696f;
```

On my machine this causes it to then use Ubuntu Mono and everything is fine. I believe this comes from Ace's default font-family rule (which I'll note also includes SourceCodePro).

**Comment by polak785** [comment]
Hello,

I have this behavior too on Firefox 70 (Ubuntu 19.04) and with the latest Kolide Fleet version. 

You still don't have plan nor time to fix this ?

**Comment by Rylon** [comment]
Just to add I also have this issue in Safari (13.1.1) on macOS Catalina 10.15.5, but it seems to be fixed in Firefox (79), did anyone figure out a workaround or fix for it?
